In [1]:
import pandas as pd
import numpy as np
import plotly.express as px

# comparacion 

6.4.2
Nivel de estrés hídrico: extracción de agua dulce como proporción de los recursos disponibles de agua dulce.  G  

Gestión integral de los recursos hídricos a todos los niveles
6n.2.1
Grado de presión sobre el recurso hídrico de las zonas centro y norte del país  N

757 cuencas hidrológicas

para desagregar, obtener estos datos por cuenca por año

1. escurrimiento natural medio superficial: ya incluido en disponibilidad superficial?
2. entradas y salidas de agua superficial de y hacia otros países
3. recarga de agua subterránea
4. caudal ecológico en los sistemas de cuencas 
5. descarga natural comprometida en acuíferos

ya se tiene:

1. disponibilidad superficial https://geosinav30metadata.conagua.gob.mx:8080/geonetwork/srv/spa/catalog.search#/metadata/9b0354df-90e3-4b8e-a656-31528f970fac
2. disponibilidad acuíferos https://geosinav30metadata.conagua.gob.mx:8080/geonetwork/srv/spa/catalog.search#/metadata/c9d72f33-5caf-4641-8620-155da91ba82c
3. volumen concesionado superficial (csurf) https://geosinav30metadata.conagua.gob.mx:8080/geonetwork/srv/spa/catalog.search#/metadata/e29b028e-d335-4c48-abe5-b2dbe8bcc2dc
4. volumen concesionado subterráneo (csub) https://geosinav30metadata.conagua.gob.mx:8080/geonetwork/srv/spa/catalog.search#/metadata/763c4995-8607-4c74-af0e-112c9c1f5e50

https://agenda2030.mx/ODSind.html?ind=ODS006000350020&cveind=407&cveCob=99&lang=es#/Indicator

$$estres=\frac{TFWW}{TRWR-EFR}\times 100\%$$

$TFWW=csurf+csub$ extracción total de agua dulce

$TRWR=IRWR+ERWR$ recursos renovables totales de agua dulce (interno + externo)

escurrimiento natural medio superficial, entradas y salidas de agua superficial de y hacia otros países, recarga de agua subterránea

$EFR=$ requisitos de caudales ambientales, cantidad y duración de de los caudales de agua dulce y niveles necesarios para sostener los ecosistemas acuáticos: caudal ecológico y descarga natural comprometida en acuíferos

superficial

2016: https://dof.gob.mx/nota_detalle.php%3Fcodigo%3D5443858%26fecha%3D07/07/2016#gsc.tab=0

 Cp.- Volumen medio anual de escurrimiento natural
Ar.- Volumen medio anual de escurrimiento desde la cuenca aguas arriba
Uc (a).- Volumen anual de extracción de agua superficial mediante títulos inscritos actualmente en el REPDA
Uc (b).- Volumen anual de extracción de agua superficial de títulos en proceso de inscripción en el REPDA
Uc (c).- Volumen anual correspondiente a las reservas, el caudal ecológico y las zonas reglamentadas
R.- Volumen anual de retornos
Im.- Volumen anual de importaciones
Ex.- Volumen anual de exportaciones
Ev.- Volumen medio anual de evaporación en embalses
Av.- Volumen medio anual de variación de almacenamiento en embalses
Ab.- Volumen medio anual de escurrimiento de la cuenca hacia aguas abajo
Rxy.- Volumen anual actual comprometido aguas abajo
D.- Disponibilidad media anual de agua superficial en la cuenca hidrológica

subterráneo

2022: https://www.dof.gob.mx/nota_detalle_popup.php?codigo=5708074

R: recarga total media anual; DNC: descarga natural comprometida; VEAS: volumen de extracción de aguas subterráneas; VCAS: volumen concesionado/asignado de aguas subterráneas; VEALA: volumen de extracción de agua en las zonas de suspensión provisional de libre alumbramiento y los inscritos en el Registro Nacional Permanente; VAPTYR: volumen de extracción de agua pendiente de titulación y/o registro en el REPDA; VAPRH: volumen de agua correspondiente a reservas, reglamentos y programación hídrica; DMA: disponibilidad media anual de agua del subsuelo. Las definiciones de estos términos son las contenidas en los numerales "3" (fracciones 3.10, 3.12, 3.18 y 3.25), y "4" (fracción 4.3), de la Norma Oficial Mexicana NOM-011-CONAGUA-2015.

$$s=\frac{TFWW}{TRWR-EFR}\times 100\%$$

$TFWW=Uca+VEAS+VCAS$$ extracción total de agua dulce

https://sinav30.conagua.gob.mx:8080/Estadistico/#/repda: REPDA por municipio: mejor usar este y desagregar los demás datos por municipio (o si no desagregar todo por estado)


volumen de agua dulce extraída de su fuente (ríos, lagos, acuíferos) para la agricultura, las industrias, y los servicios: solo estos usos?

"toma en cuenta" (suma) volúmenes concesionados de agua registrados en el Registro Público de Derechos de Agua (REPDA) e integrados en el Sistema Nacional de Información del Agua (SINA) con corte al 31 de diciembre de cada año

Uc (a).- Volumen anual de extracción de agua superficial mediante títulos inscritos actualmente en el REPDA: solo esta por municipio: entonces si esta en SINA 3.0
Uc (b).- Volumen anual de extracción de agua superficial de títulos en proceso de inscripción en el REPDA?

VEAS: volumen de extracción de aguas subterráneas; VCAS: volumen concesionado/asignado de aguas subterráneas: esta por acuifero, RHA

VEALA: volumen de extracción de agua en las zonas de suspensión provisional de libre alumbramiento y los inscritos en el Registro Nacional Permanente; VAPTYR: volumen de extracción de agua pendiente de titulación y/o registro en el REPDA?

¿cómo saber a qué cuenca o región hidrológica (RH) corresponde cada acuífero? municipiio? buscar esta información y complementar

https://sinav30.conagua.gob.mx:8080/Estadistico/#/acuiferos


$TRWR=IRWR+ERWR$ recursos renovables totales de agua dulce

agua renovable por estado (después incluir per cápita): https://sinav30.conagua.gob.mx:8080/Estadistico/#/aguaRenovable 


$IRWR$ recursos hídricos renovables internos

$ERWR$ recursos hídricos renovables externos

Cp escurrimiento natural medio superficial

Im.- Volumen anual de importaciones
Ex.- Volumen anual de exportaciones https://sinav30.conagua.gob.mx:8080/Estadistico/#/cuencas por cuenca hidrológica

R: recarga total media anual (subterránea) por acuífero https://sinav30.conagua.gob.mx:8080/Estadistico/#/acuiferos

$ERF$ requisitos de caudales ambientales

Ucc Volumen anual correspondiente a las reservas, el caudal ecológico y las zonas reglamentadas: no está en cuencas

DNC: descarga natural comprometida: por acuífero

así que comparar 2 opciones (hasta el menor grado de desagregacion que se pueda, desde 2015 hasta lo mas actual que haya):

1. tal cual en INEGI para comparar (desagregación difícil)
2. REPDA/agua renovable: 2020-2023
3. 2 pero restando ERF: no está en cuencas
4. grado de presión por RHA

Niveles de desagregación

Estado
Municipio


Región hidrológica administrativa (RHA)
Región hidrológica (RH)
Cuenca hidrológica


Ideal: todos
Posible: estado (se tienen que cortar pocos datos a vectores de estado, especialmente con segunda opción)


también comparar fuentes

## 1a. aproximación: grado de presión por RHA 2003-2022
geojson https://sinav30.conagua.gob.mx:8080/SINA/?opcion=base

In [18]:
anos = np.arange(2003,2022+1)
for ano in anos:
    f = f"../datos/Grado_de_Presion_{ano}.xlsx"
    if ano == 2003:
        gp = pd.read_excel(f,usecols=["Región Hidrológico-Administrativa","Grado de Presión (%)"])
        gp.columns = ["RHA",ano]
    else:
        gp_ano = pd.read_excel(f,usecols=["Grado de Presión (%)"])
        gp_ano.columns = [ano]
        gp[ano] = gp_ano[ano]
gp["RHA"] = gp["RHA"].str.replace(r"^\s*[IVXLCDM]+\s*[-.]?\s*", "", regex=True)
name_mapping = {
    "Península de Baja California": "Península De Baja California",
    'Cuencas Centrales del Norte': 'Cuencas Centrales Del Norte',
    "Península de Yucatán": "Península De Yucatán",
    'Aguas del Valle de México': 'Valle de México'
}
gp['RHA'] = gp['RHA'].replace(name_mapping)
gp

,RHA,2003,2004,2005,2006,2007,2008,2009,2010,2011,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,Península De Baja California,85.99,86.08,86.33,75.94,75.91,75.88,73.28,76.80,77.24,...,68.70,79.64,79.83,81.20,81.32,89.92,91.86,89.97,90.10,89.94
1,Noroeste,77.80,78.16,80.45,87.08,92.31,91.42,90.63,88.18,87.31,...,75.88,81.16,81.34,81.56,84.69,84.96,82.81,83.03,83.02,83.20
2,Pacífico Norte,42.08,42.23,41.24,40.04,40.49,40.74,40.62,40.04,40.07,...,39.43,41.93,42.08,40.59,40.42,40.46,40.05,40.23,40.44,40.51
3,Balsas,35.53,36.01,36.96,49.68,49.77,49.37,49.38,47.10,46.34,...,46.73,48.67,49.81,50.11,50.18,51.55,52.04,48.04,48.16,48.40
4,Pacífico Sur,4.15,3.89,3.93,3.94,4.10,4.12,4.15,4.37,4.44,...,4.67,5.04,5.09,5.09,5.12,5.15,5.49,5.44,5.44,5.45
5,Río Bravo,60.82,60.20,72.43,76.33,76.44,77.36,76.00,71.56,73.10,...,71.69,77.24,77.10,76.73,75.36,76.11,75.36,74.46,74.64,75.02
6,Cuencas Centrales Del Norte,54.47,54.76,55.20,45.36,49.29,48.61,48.70,45.33,46.07,...,46.63,48.42,48.39,48.38,47.65,47.85,47.53,80.89,82.78,83.03
7,Lerma-Santiago-Pacífico,32.72,35.72,36.03,40.19,40.76,41.46,41.93,42.36,41.04,...,41.99,43.57,44.82,45.42,45.18,45.63,45.84,45.64,45.72,45.91
8,Golfo Norte,19.16,19.29,19.53,17.91,18.36,18.58,18.99,18.15,19.25,...,20.55,21.00,20.42,20.78,21.13,21.38,22.00,21.97,22.03,21.02
9,Golfo Centro,4.45,4.51,4.63,4.80,5.10,5.17,5.19,5.13,5.15,...,5.18,5.73,5.85,8.58,6.43,6.61,6.80,6.75,6.77,6.42
10,Frontera Sur,1.25,1.26,1.26,1.29,1.35,1.39,1.40,1.36,1.40,...,1.37,1.62,1.73,1.45,1.73,1.72,1.78,1.68,1.69,1.70
11,Península De Yucatán,5.69,5.76,6.31,6.74,7.20,7.99,9.21,9.61,9.97,...,12.77,14.15,14.32,15.17,16.17,16.72,16.96,17.93,18.26,19.15
12,Valle de México,123.80,119.61,119.11,154.28,155.10,132.31,132.58,133.89,136.04,...,137.79,137.99,138.70,139.15,141.38,129.24,129.73,127.85,128.57,128.58

In [19]:
gp_largo = pd.melt(gp,id_vars=["RHA"],var_name="Año",value_name="Grado de presión (%)")
gp_largo["Año"] = gp_largo["Año"].astype(int)
geojson = "../datos/Región Hidrológico-Administrativa 2023.json"
fig = px.choropleth(gp_largo,geojson=geojson,locations="RHA",featureidkey="properties.rha",color="Grado de presión (%)",animation_frame="Año",color_continuous_scale="Viridis")
fig.update_geos(fitbounds="locations",visible=False)
fig.update_layout(margin={"r":0,"t":0,"l":0,"b":0})
fig.show()

In [20]:
px.line(gp_largo,x="Año",y="Grado de presión (%)",color="RHA")

In [36]:
years = np.arange(2020, 2023 + 1)
for year in years:
    f = f"../datos/repda_estatal{year}.xlsx"

    if year == 2020:
        repda = pd.read_excel(f, usecols=["Estado", "Total por estado"])
        repda.columns = ["Estado", year]
        repda[year] = (
            repda[year]
            .astype(str)
            .str.replace(",", "", regex=False)
            .str.replace(r"[^\d.\-]", "", regex=True)
        )
        repda[year] = pd.to_numeric(repda[year], errors="coerce")
    else:
        repda_year = pd.read_excel(f, usecols=["Total por estado"])
        repda_year.columns = [year]
        repda_year[year] = (
            repda_year[year]
            .astype(str)
            .str.replace(",", "", regex=False)
            .str.replace(r"[^\d.\-]", "", regex=True)
        )
        repda_year[year] = pd.to_numeric(repda_year[year], errors="coerce")
        repda[year] = repda_year[year]

repda

                             Estado      2020      2021      2022      2023
0                    Aguascalientes    641.42    641.42    641.42    641.42
1                   Baja California   3472.88   3472.88   3472.88   3472.88
2               Baja California Sur    438.76    438.76    438.76    438.76
3                          Campeche   1840.23   1840.23   1840.23   1840.23
4              Coahuila de Zaragoza   2702.37   2702.37   2702.37   2702.37
5                            Colima   1774.54   1774.54   1774.54   1774.54
6                           Chiapas  62670.67  62670.67  62670.67  62670.67
7                         Chihuahua   7763.70   7763.70   7763.70   7763.70
8                  Ciudad de México    603.47    603.47    603.47    603.47
9                           Durango   1842.57   1842.57   1842.57   1842.57
10                       Guanajuato   4940.64   4940.64   4940.64   4940.64
11                         Guerrero  20308.96  20308.96  20308.96  20308.96
12                          Hidalgo   3657.31   3657.31   3657.31   3657.31
13                          Jalisco  14011.75  14011.75  14011.75  14011.75
14                           México   5504.66   5504.66   5504.66   5504.66
15                        Michoacán  32359.23  32359.23  32359.23  32359.23
16                          Morelos   1341.17   1341.17   1341.17   1341.17
17                          Nayarit  14337.48  14337.48  14337.48  14337.48
18                       Nuevo León   2038.46   2038.46   2038.46   2038.46
19                           Oaxaca  18347.35  18347.35  18347.35  18347.35
20                           Puebla   7424.43   7424.43   7424.43   7424.43
21                        Querétaro   1033.74   1033.74   1033.74   1033.74
22                     Quintana Roo   1250.52   1250.52   1250.52   1250.52
23                  San Luis Potosí   2691.29   2691.29   2691.29   2691.29
24                          Sinaloa  19924.23  19924.23  19924.23  19924.23
25                           Sonora  12000.74  12000.74  12000.74  12000.74
26                          Tabasco    689.66    689.66    689.66    689.66
27                       Tamaulipas   5910.18   5910.18   5910.18   5910.18
28                         Tlaxcala    281.08    281.08    281.08    281.08
29  Veracruz de Ignacio de la Llave  11370.24  11370.24  11370.24  11370.24
30                          Yucatán   2464.73   2464.73   2464.73   2464.73
31                        Zacatecas   1711.57   1711.57   1711.57   1711.57